name: bump_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_vertexai: ^0.2.2+3
  firebase_storage: ^12.1.2
  http: ^1.2.2
  # flutter_widget_from_html: ^0.15.1
  xml: ^6.5.0
  image_picker: ^1.1.2
  cross_file_image: ^1.1.0
  # mime: ^1.0.5
  # svg_clip: ^0.0.2
  # path_drawing: ^1.0.1
  # scribble: ^0.10.0+1
  # scroll_datetime_picker: ^0.1.2
  html: ^0.15.4
  flutter_markdown: ^0.7.3+1
  lottie: ^3.1.2
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
